//! The topology-informed adversary (M11 / spec §19): expose the COMPLETE state
//! machine to the attacker and prove the knowledge buys nothing.
//!
//! BLD's security is structural, not obscurity — the transition graph is even
//! *exported* (`docs/topology.json`, generated by running the domain). This test
//! reads that exported graph, and for every state it can reach, fires every
//! transition the graph marks **`no_edge`** (an edge that does not exist — an
//! illegal move) at the live boundary, with a well-formed body so the ONLY thing
//! wrong is that the move is illegal. Every one must be refused as `Undefined`
//! (409) and leave the booking exactly where it was.
//!
//! An adversary holding the whole graph can target every illegal edge precisely.
//! The claim is that the boundary blocks all of them regardless — and because the
//! test derives its attacks from the exported topology, it stays honest if the
//! graph ever changes.

use bld_client::{BldClient, ClientError, discover};
use bld_manifest::signing_key_from_hex;
use std::collections::{BTreeMap, BTreeSet};
use townhall_testkit::{MANIFEST_KEY_HEX, world_discoverable};

const BEARER: &str = "dev-lucy";
const PRINCIPAL: &str = "lucy";
const RESOURCE: &str = "booking-intents";

/// The full behaviour vocabulary — every input the proposal door names.
const VOCABULARY: &[&str] = &[
    "SelectVenue",
    "VerifySlot",
    "ChangeVenue",
    "UpdateRequirements",
    "RevalidateVenue",
    "Book",
    "Cancel",
];

/// A well-formed body for each behaviour, so an out-of-menu attack is refused for
/// being ILLEGAL (Undefined), not for a malformed body.
fn plausible_body(behaviour: &str) -> serde_json::Value {
    match behaviour {
        "SelectVenue" | "ChangeVenue" => {
            serde_json::json!({ "venue_id": "TH-A", "slot_id": "SLOT-A" })
        }
        "UpdateRequirements" => serde_json::json!({ "attendees": 20 }),
        "Cancel" => serde_json::json!({ "reason": "adversarial probe" }),
        _ => serde_json::json!({}),
    }
}

fn create_body(id: &str) -> serde_json::Value {
    serde_json::json!({
        "id": id, "purpose": "community meeting", "requested_date": "2026-09-15",
        "from": "13:00", "to": "17:00", "attendees": 20,
        "wheelchair_accessible": true, "max_fee_pence": 5_000,
    })
}

/// Parse the exported topology into `state -> {illegal (no_edge) inputs}`.
fn illegal_edges() -> BTreeMap<String, BTreeSet<String>> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/topology.json");
    let raw = std::fs::read_to_string(&path).expect("read docs/topology.json");
    let json: serde_json::Value = serde_json::from_str(&raw).expect("parse topology.json");

    let door = json["doors"]
        .as_array()
        .expect("doors")
        .iter()
        .find(|d| d["name"] == "proposal")
        .expect("the proposal door");

    let mut map: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for cell in door["cells"].as_array().expect("cells") {
        if cell["edge"] == "no_edge" {
            let from = cell["from"].as_str().unwrap().to_owned();
            let input = cell["input"].as_str().unwrap().to_owned();
            map.entry(from).or_default().insert(input);
        }
    }
    map
}

async fn client(world_url: &str, http: reqwest::Client, booking: &str) -> BldClient {
    let verifying = signing_key_from_hex(MANIFEST_KEY_HEX)
        .expect("key")
        .verifying_key();
    let discovered = discover(&http, world_url, &verifying)
        .await
        .expect("manifest verifies");
    BldClient::new(
        discovered,
        http,
        PRINCIPAL,
        BEARER,
        Some(booking.to_owned()),
    )
}

async fn read_state(client: &BldClient, id: &str) -> String {
    client
        .read(RESOURCE, id)
        .await
        .map_or_else(|_| "<unreadable>".to_owned(), |f| f.state)
}

/// Fire every illegal edge the exported graph declares from `state`, and assert
/// the boundary refuses each as Undefined (409) and never moves the booking.
async fn probe_illegal_edges(client: &BldClient, id: &str, state: &str) {
    let illegal = illegal_edges();
    let attacks: Vec<&String> = illegal
        .get(state)
        .map(|set| set.iter().collect())
        .unwrap_or_default();
    assert!(
        !attacks.is_empty(),
        "the topology must declare SOME illegal edge from {state} for this probe to mean anything"
    );

    let version = client.read(RESOURCE, id).await.expect("read").version;
    for behaviour in attacks {
        // Sanity: the adversary is only firing edges the graph calls illegal.
        assert!(
            VOCABULARY.contains(&behaviour.as_str()),
            "unknown behaviour {behaviour}"
        );
        let result = client
            .drive(RESOURCE, id, behaviour, plausible_body(behaviour), version)
            .await;
        match result {
            Err(ClientError::Refused { status, .. }) => assert_eq!(
                status, 409,
                "illegal edge {state} --{behaviour}--> must be Undefined (409), got {status}"
            ),
            other => panic!("illegal edge {state} --{behaviour}--> was NOT refused: {other:?}"),
        }
        assert_eq!(
            read_state(client, id).await,
            state,
            "the illegal {behaviour} from {state} changed the state — an illegal transition slipped through"
        );
    }
}

#[tokio::test]
async fn no_illegal_edge_is_reachable_from_any_state_the_adversary_can_stand_in() {
    let world = world_discoverable();

    // Reach each state on the ordinary (below-threshold) path, then probe it.
    // "Draft" — freshly created.
    {
        let c = client(&world.server_url, reqwest::Client::new(), "TOPO-DRAFT").await;
        c.create(RESOURCE, create_body("TOPO-DRAFT"))
            .await
            .expect("draft");
        probe_illegal_edges(&c, "TOPO-DRAFT", "Draft").await;
    }
    // "VenueSelected".
    {
        let c = client(&world.server_url, reqwest::Client::new(), "TOPO-VS").await;
        let f = c
            .create(RESOURCE, create_body("TOPO-VS"))
            .await
            .expect("draft");
        c.drive(
            RESOURCE,
            "TOPO-VS",
            "SelectVenue",
            serde_json::json!({"venue_id":"TH-A","slot_id":"SLOT-A"}),
            f.version,
        )
        .await
        .expect("select");
        probe_illegal_edges(&c, "TOPO-VS", "VenueSelected").await;
    }
    // "AwaitingBooking" (£45 < £100 default threshold → no payment).
    {
        let c = client(&world.server_url, reqwest::Client::new(), "TOPO-AB").await;
        let f = c
            .create(RESOURCE, create_body("TOPO-AB"))
            .await
            .expect("draft");
        let f = c
            .drive(
                RESOURCE,
                "TOPO-AB",
                "SelectVenue",
                serde_json::json!({"venue_id":"TH-A","slot_id":"SLOT-A"}),
                f.version,
            )
            .await
            .expect("select");
        let f = c
            .drive(
                RESOURCE,
                "TOPO-AB",
                "VerifySlot",
                serde_json::json!({}),
                f.version,
            )
            .await
            .expect("verify");
        assert_eq!(f.state, "AwaitingBooking");
        probe_illegal_edges(&c, "TOPO-AB", "AwaitingBooking").await;
    }
    // "Booked" (drive through, then let the reconciler converge).
    {
        let c = client(&world.server_url, reqwest::Client::new(), "TOPO-BK").await;
        let f = c
            .create(RESOURCE, create_body("TOPO-BK"))
            .await
            .expect("draft");
        let f = c
            .drive(
                RESOURCE,
                "TOPO-BK",
                "SelectVenue",
                serde_json::json!({"venue_id":"TH-A","slot_id":"SLOT-A"}),
                f.version,
            )
            .await
            .expect("select");
        let f = c
            .drive(
                RESOURCE,
                "TOPO-BK",
                "VerifySlot",
                serde_json::json!({}),
                f.version,
            )
            .await
            .expect("verify");
        let _ = c
            .drive(
                RESOURCE,
                "TOPO-BK",
                "Book",
                serde_json::json!({}),
                f.version,
            )
            .await
            .expect("book");
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(10);
        while read_state(&c, "TOPO-BK").await != "Booked" && std::time::Instant::now() < deadline {
            std::thread::sleep(std::time::Duration::from_millis(100));
        }
        assert_eq!(read_state(&c, "TOPO-BK").await, "Booked", "reached Booked");
        probe_illegal_edges(&c, "TOPO-BK", "Booked").await;
    }
}
